on:
  push:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [dev, staging, production]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v5

      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ matrix.branch }}

      - run: gh pr merge --auto --merge ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
